image: node:24.10.0-alpine

workflow:
    rules:
        -   if: $CI_MERGE_REQUEST_DRAFT
            when: never
        -   if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release.*/ && $CI_MERGE_REQUEST_APPROVED

default:
    before_script:
        - corepack enable pnpm
        # Stupidly enough, `pnpm` does not have a `no-interactive` mode and can thus block stdin...
        - yes | pnpm setup
        - . ~/.bashrc
        - pnpm i -g firebase-tools
        - pnpm i

stages:
    - build
    - test
    - deploy

### JOBS ###

build:
    stage: build
    script:
        - pnpm run unsafe:build
    artifacts:
        paths:
            - dist/
        expire_in: 2 mins 30 sec

audit:
    stage: test
    script:
        - pnpm audit
    dependencies:
        - build

lint:
    stage: test
    script:
        - pnpm run unsafe:lint
    dependencies:
        - audit

deploy:
    stage: deploy
    environment: production
    script:
        - npm config set //registry.npmjs.org/:_authToken "${NPM_SOLIDWEATHER_ACCESS_TOKEN}"
        - npm publish --access public
    dependencies:
        - lint