image: node:24.10.0-alpine

workflow:
    rules:
        -   if: $CI_COMMIT_BRANCH =~ /^release.*/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
            when: always
        -   when: never

default:
    before_script:
        - rm package-lock.json
        - rm -rf node_modules
        - npm i

stages:
    - test
    - deploy

### JOBS ###

audit:
    stage: test
    script:
        - npm audit

lint:
    stage: test
    script:
        - npm run unsafe:lint
    dependencies:
        - audit

deploy:
    stage: deploy
    environment: production
    script:
        - npm run unsafe:build
        - npm config set //registry.npmjs.org/:_authToken "${NPM_SOLIDWEATHER_ACCESS_TOKEN}"
        - npm publish --access public
    dependencies:
        - lint