/*
 * Copyright (c) 2025 Axel "Foley" Karlsson and contributors.
 *
 * Use of this source code is governed by the MIT License, which you may
 * view in its entirety in the LICENSE file, found in the project's root directory.
 */

import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import fs from "node:fs"
import { defineConfig, loadEnv } from "vite"
import react from "@vitejs/plugin-react"

const __dirname = dirname(fileURLToPath(import.meta.url))

function writeSassConstants(constants: Record<string, string>): void {

    let content =
        "/*!\n" +
        " * Copyright (c) 2025 Axel \"Foley\" Karlsson and contributors.\n" +
        " *\n" +
        " * Use of this source code is governed by the MIT License, which you may\n" +
        " * view in its entirety in the LICENSE file, found in the project's root directory.\n" +
        " */\n" +
        "\n" +
        "// --- DO NOT EDIT THIS FILE; IT IS AUTOMATICALLY GENERATED ---\n"

    for (const [key, value] of Object.entries(constants)) {
        content += `$${key}: "${value}"\n`
    }

    fs.writeFileSync(resolve(__dirname, "src/sass/_dynamic_constants.sass"), content)
}

export default defineConfig(({ mode }) => {

    const env = loadEnv(mode, process.cwd(), "")

    if (!env.VITE_COMPONENT_PREFIX) {
        throw Error("VITE_COMPONENT_PREFIX is undefined.")
    }
    
    writeSassConstants({
        prefix: env.VITE_COMPONENT_PREFIX
    })

    return {
        plugins: [
            react({
                babel: {
                    plugins: [ "babel-plugin-react-compiler" ]
                }
            })
        ],

        build: {
            // We do not want vite to clear the generated d.ts files.
            emptyOutDir: false,

            lib: {
                entry: resolve(__dirname, "./src/index.ts"),
                name: "SolidWeather-Components",
                cssFileName: "index"
            },

            rollupOptions: {
                external: [ "react", "react-dom" ],
                output: {
                    globals: {
                        "react": "React"
                    }
                }
            },

            license: true
        },

        css: {
            preprocessorOptions: {
                sass: {
                    loadPaths: ["src/sass"]
                }
            }
        },

        server: {
            // Required for the dev server to be accessible outside the Docker container.
            host: "0.0.0.0",

            watch: {
                usePolling: true
            }
        },

        resolve: {
            alias: {
                "@": resolve(__dirname, "./src")
            }
        }
    }
})